### PR TITLE
Allow repeated names of interviews and automatically add a numerical identifier to identify each interview

### PR DESCRIPTION
**Pull request by AustinHuang1203**

### CODE REVIEW

**Review by craigtonlian — COMMENTED** [review]
I don't think it is expected behavior that adding a same-name-interview will result in the interview being added after having it's type incremented by an arbitrary end digit.

For example, if the user attempts to add a duplicate applicant into the system, should the program decide the intentions of the user and append a "numerical identifier" suffix to the applicant name? Or should the program alert the user of the potential duplicate entry, and allow the user to edit his command to disambiguate in any way the user chooses?

Other errors may also arise from this naive approach of handling duplicates. For example, if an applicant has a single existing interview named "leetcode292", then adding a duplicate interview will result in "leetcode293" being added to the interview list, which is not expected behavior.

@jingting1412 @ivanleekk @CelestineTan03 what do you think of this duplicate handling?

**Comment by AustinHuang1203** [comment]
Adding a 1 and incrementing it is exactly how some OS/applications handles duplicate files so its standard industry practice. And I did not make the change for applicant name, only interview as it is possible and even likely that a candidate will have more than 1 technical round but the chance of 2 candidates having the exact name is much lower in comparison.

It is expected behaviour if i key in leetcode293 twice that it will increment the number behind. In the first place, why will the hiring manager be adding 2 of the same interview to the system unless its 2 different interviews which should be named differently.

**Comment by craigtonlian** [comment]
> Adding a 1 and incrementing it is exactly how some OS/applications (even Canvas assignments) handles duplicate files so its standard industry practice. So this "naive" approach is being used by millions of people worldwide. If you can propose a better solution than the "naive" approach of what millions of people and many applications have used, I would be interested in hearing it. Maybe even Microsoft would want an audience with you! 

1. Which OS are you refering to that adds a 1 and increments it when adding a same-name-file? This appears to not be the case for Ubuntu, nor macOS, not Windows. They all verify with the user if the user intends to overwrite the existing file and allows the user to decide the duplicate handling.

2. Canvas assignments are expected to have multiple submissions of the same name due to the filename convention enforced by the course coordinator, hence that internal renaming system is warranted. And even in that situation when it is warranted, it has still caused a lot of confusion amongst students when their uploaded file reflects a different name from the file they chose to upload. This is corroborated by the many emails that TAs receive during assignment submission.

>why will the hiring manager be adding 2 of the same interview to the system unless its 2 different interviews which should be named differently.

3. As you have aptly pointed out, there is never a need to legitimately add two of the same interviews to the Staff-Snap, hence the system should not allow duplicate interviews to be added. This leads to the need to throw an error message to the user, informing them to adjust their interview type to disambiguate. So I'm not sure if this PR solves a problem or creates more confusion.

> As GPT says:
In the context of a human resources (HR) tracking system where interviews might have the same name, a more automated approach, like incrementing numerical identifiers, may be more practical and user-friendly. Here's why:

4. I appreciate your effort to parrot GPT's response but, sadly, ChatGPT is neither an authority nor a a remotely relevant reference for design decisions. I hope you recognise the universal truth that will be ill-advised to make design decisions based primarily on GPT's response.

**Comment by AustinHuang1203** [comment]
1. Try downloading the same file from some website multiple times and see what the naming convention is.
2. Once again, nothing is perfect. I would assume if a design decision is suitable for an application with that many users, it would be more suitable for a small project like this.
3. If the HR did give the interview a number, it means they are seperating interviews of the same type and adding 2 interviews with the same number is not likely. This change is for when the HR person does not want to manually seperate interviews of the same type.
4. Ok, so who is the authority for design decisions? You?

**Comment by ivanleekk** [comment]
I think that purely from a user POV, if I have multiple rounds of interviews I would have some sort of process or SOP in place for what to call each round of interviews. I would probably not have two interviews that are named the exactly the same as that would be confusing for the team. Take this diagram as an example, even the similar in scope round 2 and 3 are differentiated in name, one is called a technical quiz whilst the other is called a technical interview, which takes away from the ambiguity of which stage the applicant is in, or where relevant comments or observations may have been made.

image

However if you do feel very strongly for this feature, as Prof Damith said on Teams if no one else feels that their features will be affected by it then sure I guess we can merge this PR and carry on. I sincerely hope that we can keep up with friendly discussions and that no one takes reviews as a personal attack, it is just work after all and we all want the best for each other 🤗

**Review by CelestineTan03 — COMMENTED** [review]
I agree with @craigtonlian and @ivanleekk. To add on, considering that we are planning to limit the number of characters for the interview name, adding a numerical identifier to the back of the interview name can cause errors when the interview name is already at max length. Hence, although this can be a good way to handle duplicate names in some cases, I feel that it is not the best fit for our case 😄

**Comment by AustinHuang1203** [comment]
Maybe you should have told me all of this during one of your secret meetings hm? In any case, you can limit interview name length to max length - 1 and max interviews to 9 or less to resolve this issue.

**Pull request merged**
