### PR TITLE
Implement additional sorting features

### LINKED ISSUE #98: Sort applicant list by rating

### LINKED ISSUE #127: Fix FilterCommand by name not ignoring case

### PR DESCRIPTION
**Pull request by ivanleekk**
Sort by

- [x] Rating
- [x] Email
- [x] Position
- [x] Status

Sort in

- [x] Ascending order
- [x] Descending order

TODO:

- [x] Add test cases

closes #98 
closes #127

### CODE REVIEW

**Review by AustinHuang1203 — COMMENTED** [review]
Some test cases failing causing the build to not pass the ci/cd checks, can remove or change them to pass.

**Comment by ivanleekk** [comment]
> Some test cases failing causing the build to not pass the ci/cd checks, can remove or change them to pass.

Jus pushed a fix for this, should be working now

**Review by craigtonlian — COMMENTED** [review]
Calling `filter p/software engineer` results in a runtime error! Perhaps a wrong subfunction was mistakenly called 😄

**Review by craigtonlian — APPROVED** [review]
Lgtm! Thanks Ivan!

**Pull request merged**
